import type { AuditEvent, Finding, Patient, Scenario } from './types'

export const patients: Patient[] = [
  { id: 'demo-allergy', name: 'Maya Thompson', initials: 'MT', age: 67, sex: 'Female', mrn: 'DEMO-ALLERGY', dob: '1959-03-14', flags: ['Penicillin allergy'] },
  { id: 'demo-warfarin', name: 'Daniel Brooks', initials: 'DB', age: 74, sex: 'Male', mrn: 'DEMO-WARFARIN', dob: '1952-08-02', flags: ['Warfarin'] },
  { id: 'demo-pregnancy', name: 'Sofia Martinez', initials: 'SM', age: 32, sex: 'Female', mrn: 'DEMO-PREGNANCY', dob: '1994-01-22', flags: ['Pregnant'] },
  { id: 'demo-simvastatin', name: 'Elliot Nguyen', initials: 'EN', age: 58, sex: 'Male', mrn: 'DEMO-SIMVASTATIN', dob: '1968-11-09', flags: ['Simvastatin'] },
]

const warfarinFinding: Finding = {
  id: 'DDI-0041', severity: 'critical', title: 'Major drug-drug interaction',
  explanation: 'Ibuprofen may increase bleeding risk when combined with warfarin.',
  patientFact: 'Active medication: warfarin 5 mg once daily',
  evidence: 'Concomitant NSAID and anticoagulant therapy is associated with increased bleeding risk.',
  source: 'DDInter snapshot 2026.09 · row 118422', action: 'Do not continue without clinician review and a safer analgesic plan.', certainty: 'high',
}

export const scenarios: Scenario[] = [
  { id: 'safe', title: 'No conflict found', summary: 'A routine recommendation with sufficient context.', severity: 'pass', patientId: 'pat-00482', prompt: 'Review acetaminophen for mild knee pain.', output: 'Consider acetaminophen 500 mg orally every 6 hours as needed, maximum 3,000 mg per day.', findings: [] },
  { id: 'allergy', title: 'Allergy conflict', summary: 'AI proposes a drug from a documented allergy class.', severity: 'critical', patientId: 'pat-00482', prompt: 'Suggest an antibiotic for suspected bacterial sinusitis.', output: 'Start amoxicillin 500 mg orally three times daily for 7 days.', findings: [{ id: 'ALG-0012', severity: 'critical', title: 'Documented allergy conflict', explanation: 'The proposed medication belongs to the same class as a documented allergy.', patientFact: 'Allergy: penicillin · reaction: urticaria', evidence: 'Amoxicillin is a penicillin-class antibacterial.', source: 'RxNorm/RxClass 2026.10 · class N0000175560', action: 'Choose a non-penicillin alternative after clinical review.', certainty: 'high' }] },
  { id: 'warfarin', title: 'Warfarin + ibuprofen', summary: 'High-risk anticoagulant and NSAID combination.', severity: 'critical', patientId: 'pat-01091', prompt: 'Recommend an option for acute back pain.', output: 'Start ibuprofen 600 mg orally every 8 hours with food for 5 days.', findings: [warfarinFinding] },
  { id: 'statin', title: 'Statin interaction', summary: 'CYP3A4 interaction with clarithromycin.', severity: 'critical', patientId: 'pat-00207', prompt: 'Recommend treatment for community-acquired pneumonia.', output: 'Start clarithromycin 500 mg orally twice daily for 7 days.', findings: [{ id: 'DDI-0088', severity: 'critical', title: 'Severe interaction with simvastatin', explanation: 'Clarithromycin can increase simvastatin exposure and risk of myopathy.', patientFact: 'Active medication: simvastatin 40 mg nightly', evidence: 'Concurrent use is contraindicated in the referenced label.', source: 'openFDA label snapshot · SETID 7c8f', action: 'Select a non-interacting antibiotic or hold statin per clinician judgment.', certainty: 'high' }] },
  { id: 'pregnancy', title: 'Pregnancy concern', summary: 'Recommendation conflicts with pregnancy context.', severity: 'critical', patientId: 'pat-00814', prompt: 'Suggest therapy for acne.', output: 'Begin isotretinoin 20 mg orally once daily.', findings: [{ id: 'PREG-0003', severity: 'critical', title: 'Pregnancy contraindication', explanation: 'The proposed medication has a serious fetal risk.', patientFact: 'Pregnancy status: active · estimated 12 weeks', evidence: 'Isotretinoin is contraindicated during pregnancy.', source: 'openFDA label snapshot · boxed warning', action: 'Do not initiate; route to urgent clinician review.', certainty: 'high' }] },
  { id: 'renal', title: 'Renal dose concern', summary: 'Dose is unsafe for documented renal function.', severity: 'caution', patientId: 'pat-00482', prompt: 'Draft a gabapentin plan for neuropathic pain.', output: 'Start gabapentin 900 mg orally three times daily.', findings: [{ id: 'RENAL-0021', severity: 'caution', title: 'Dose requires renal review', explanation: 'The proposed daily dose may exceed limits for reduced renal function.', patientFact: 'Most recent eGFR: 42 mL/min/1.73m²', evidence: 'Dose adjustment is recommended in renal impairment.', source: 'openFDA label snapshot · renal impairment', action: 'Confirm creatinine clearance and use a renal-adjusted regimen.', certainty: 'moderate' }] },
  { id: 'dose', title: 'Excessive dose', summary: 'Frequency exceeds the configured policy limit.', severity: 'critical', patientId: 'pat-00482', prompt: 'Suggest acetaminophen dosing for pain.', output: 'Take acetaminophen 1,000 mg every 4 hours around the clock.', findings: [{ id: 'DOSE-0017', severity: 'critical', title: 'Maximum daily dose exceeded', explanation: 'The proposed schedule totals 6,000 mg per day.', patientFact: 'No current acetaminophen order found', evidence: 'Configured prototype maximum: 3,000 mg/day for this patient profile.', source: 'PramanRx policy set 0.4.0 · DOSE-0017', action: 'Reduce total daily dose and verify all combination products.', certainty: 'high' }] },
  { id: 'missing', title: 'Missing critical context', summary: 'Renal status is required but unavailable.', severity: 'insufficient', patientId: 'pat-00482', prompt: 'Recommend an anticoagulant dose.', output: 'Start apixaban 5 mg orally twice daily.', findings: [{ id: 'CTX-0009', severity: 'insufficient', title: 'Required renal context unavailable', explanation: 'A recent renal function result is required for this policy.', patientFact: 'No eGFR in the last 180 days', evidence: 'Renal function is a required input for dose verification.', source: 'PramanRx policy set 0.4.0 · CTX-0009', action: 'Obtain current renal function before relying on this recommendation.', certainty: 'high' }] },
  { id: 'unknown', title: 'Unknown medication', summary: 'Medication cannot be normalized to RxNorm.', severity: 'insufficient', patientId: 'pat-00482', prompt: 'Review the proposed new medication.', output: 'Start CardioZen-XR 25 mg each morning.', findings: [{ id: 'NORM-0004', severity: 'insufficient', title: 'Medication could not be identified', explanation: 'No unambiguous normalized concept was found.', patientFact: 'Proposed text: CardioZen-XR', evidence: 'No exact or high-confidence match in local RxTerms snapshot.', source: 'RxTerms 2026.10 · local snapshot', action: 'Confirm the intended medication and structured code.', certainty: 'high' }] },
  { id: 'malformed', title: 'Malformed AI output', summary: 'Untrusted response fails the recommendation contract.', severity: 'insufficient', patientId: 'pat-00482', prompt: 'Return a structured medication recommendation.', output: '{ "medication": "lisinopril", "dose": [ERROR', findings: [{ id: 'INPUT-0002', severity: 'insufficient', title: 'Recommendation payload is malformed', explanation: 'The response cannot be safely parsed into the expected contract.', patientFact: 'No verified medication proposal available', evidence: 'JSON parser stopped at character 39.', source: 'Recommendation contract v1.2', action: 'Request a corrected response; do not infer missing fields.', certainty: 'high' }] },
  { id: 'invalid-kb', title: 'Invalid KB signature', summary: 'Knowledge artifact integrity check fails closed.', severity: 'integrity', patientId: 'pat-00482', prompt: 'Evaluate any proposed medication.', output: 'Start lisinopril 10 mg orally once daily.', findings: [{ id: 'INT-0001', severity: 'integrity', title: 'Knowledge artifact integrity failure', explanation: 'The local artifact signature does not match its signed manifest.', patientFact: 'Evaluation halted before clinical policy execution', evidence: 'Ed25519 signature verification: failed', source: 'KB artifact prx-kb-2026.10.0', action: 'Quarantine artifact and restore a verified signed version.', certainty: 'high' }] },
  { id: 'tamper', title: 'Audit tampering', summary: 'A historical event no longer matches its chain hash.', severity: 'integrity', patientId: 'pat-01091', prompt: 'Verify the audit history.', output: 'Historical recommendation record.', findings: [{ id: 'AUD-0001', severity: 'integrity', title: 'Audit chain verification failed', explanation: 'Event 8 does not match the stored previous hash.', patientFact: 'Request req_7B21 · patient SYN-01091', evidence: 'Expected 91d0…a032; observed 44e7…b991', source: 'Audit chain v1 · SHA-256', action: 'Lock record, alert security, and investigate provenance.', certainty: 'high' }] },
]

export const auditEvents: AuditEvent[] = [
  { id: 'evt_01', time: '10:42:18.084', title: 'Request created', actor: 'Dr. Lena Ortiz', detail: 'Request req_8F31 bound to patient pat-01091', hash: 'sha256:68c41b36b212a902', verified: true },
  { id: 'evt_02', time: '10:42:18.129', title: 'AI output frozen', actor: 'adapter:ollama', detail: 'Immutable recommendation digest recorded', hash: 'sha256:2f9e87a13e11cfe3', verified: true },
  { id: 'evt_03', time: '10:42:18.301', title: 'Patient context retrieved', actor: 'pramanrx:context', detail: 'FHIR bundle mapped to PatientContext v1.3', hash: 'sha256:913ac514e618bf99', verified: true },
  { id: 'evt_04', time: '10:42:18.366', title: 'KB integrity verified', actor: 'pramanrx:kb', detail: 'Ed25519 signature and source checksums passed', hash: 'sha256:e51ec887c4c88d40', verified: true },
  { id: 'evt_05', time: '10:42:18.421', title: 'Critical verdict issued', actor: 'pramanrx:policy', detail: 'DDI-0041 matched warfarin + ibuprofen', hash: 'sha256:bb785489d3174aae', verified: true },
]
